#!/usr/bin/env bash

pushd $(dirname $1) > /dev/null
INPUTPATH=$(pwd)/$(basename $1)
OUTDIR=$(pwd)
popd > /dev/null
SCRIPTPATH=$(dirname "$BASH_SOURCE")
pushd $SCRIPTPATH > /dev/null
cargo run --bin creusot-rustc --  \
  --output-file="${INPUTPATH%.*}.noopt2.mlcfg" \
  --span-mode=absolute \
  --tiopt-elide=false \
  --tiopt-clone=false \
  --tiopt-para=false \
  -- -Zno-codegen \
  -Zmacro-backtrace \
  --extern creusot_contracts=./target/debug/libcreusot_contracts.rlib \
  -Ldependency=./target/debug/deps/ \
  --crate-type=lib \
  $INPUTPATH
popd > /dev/null
